---
title: "The Ridge Regression"
author: "Clint Guo"
date: "`r Sys.Date()`"
output:
  html_document:
    self_contained: yes
    toc: yes
---
<!--
%\VignetteEngine{knitr::rmarkdown}
%\VignetteIndexEntry{The ridge regression vignette}
-->

## The ridge_reg function

```{r}
library(bis557)
data(ridge_train)
data(ridge_test)
ridge_train_scale <- as.data.frame(scale(ridge_train))
ridge_test_scale <- as.data.frame((scale(ridge_test)))
formula <- y ~. -1
```

The function is to calculate mse of the ridge regression model for different lambda values.

```{r}
mse_ridge_reg <- function(lambda){ 
  X_test <- model.matrix(formula, ridge_test_scale)
  y_test <- ridge_test_scale[, all.vars(formula)[1]]
  k <- length(lambda)
  mse <- rep(NA_real_, k)
  for (j in 1:k) {
    ridge_beta <- ridge_reg(formula, lambda[j], ridge_train_scale)
    y_hat <- X_test %*% ridge_beta$coefficients
    mse[j] <- mean((y_hat - y_test) ^ 2)
  }
  return(mse)
}
```

We are able to find the optimal value of lambda and plot lambdas on a log scale with their corresponding mses.

```{r}
lambda_vals <- 10 ^ (seq(-1, 5, 0.1))
mse <- mse_ridge_reg(lambda_vals)
lambda_optimal <- lambda_vals[which.min(mse)]
cat("The optimal value of lambda is", lambda_optimal, "\n")
plot(mse ~ lambda_vals, log = "x", pch = 16)
```

